# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  # - name: Timeline
  #   url: blog/
  #   weight: 30
  # - name: Showcase
  #   url: showcase/
  #   weight: 40
  - name: Contact
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: contact
    name: "Contact"
    pageRef: "/community"
    weight: 2
  - identifier: codabench
    name: "CodaBench ↗"
    url: "https://codabench.org"
    weight: 3
